### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by Rathna-K** [bikerp/dsp-w215-hnap#15]
Hi @thunderbird @bikerp @Bananis, not sure if you guys still interested in this but thank you for sharing your work here. With D-Link pulling IFTTT support, thought of controlling W110 plug with this script but I am getting login error : here are the details: 

/dsp-w215-hnap/node_modules/promise/lib/done.js:10
      throw err;
      ^
Login failed!
Thrown at:
    at /dsp-w215-hnap/node_modules/promise/lib/done.js:10:7
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by bikerp** [comment]
Hi @Rathna-K , as the error says login failed. Did you fill the correnct credentials and IP address?

**Comment by Rathna-K** [comment]
the login info is correct but the device is a W110, would that be the issue? if so any idea how to make it work? TIA

**Comment by bikerp** [comment]
I have only tested on W215
